### PR TITLE
Fix broken placeholder text on empty content

### LINKED ISSUE #84: broken placeholder text
Given that we've now added paragraphs to the editor, the default HTML of the editor is `<p><br></p>` which breaks the placeholder text shown in it. Previously it was empty and the placeholder would show, it can also be shown be clicking in the editor and pressing Backspace.

Consider moving the current CSS from 
```
#editor:empty:not(:focus):before, #editor:empty:focus:before {
    content: attr(data-placeholder);
    color: #C9C9C9;
}
```
to JavaScript that renders this if the innerHTML of the editor is `<p><br></p>`, or I assume some similar solution.

The corrent behavior should be to show the placeholder only if the editor's inner HTML is `<p><br></p>`.

### PR DESCRIPTION
**Pull request by stackoversnow**
broken_placeholder

Fixes #84

### CODE REVIEW

File: src/app/home/home.component.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export class HomeComponent implements AfterViewInit {
     displayWriteTextOrUploadDocumentFlag: any = true;
     characterCount: number = 0;
     wordCount: number = 0;
-    innerHTMLOfEditor: any = this.LINE_BROKEN_PARAGRAPH;
```
Comment (AndiBraimllari) [inline src/app/home/home.component.ts:31]: This and then the following `document.getElementById(this.EDITOR_KEY)!.innerHTML = this.LINE_BROKEN_PARAGRAPH;` lines should not be changed. A solution must be tailored with these in mind.

**Review by AndiBraimllari — CHANGES_REQUESTED** [review]

**Comment by AndiBraimllari** [comment]
Hey, thanks for the PR!

I've added my comment.

I'll need to address the pipeline issue in some other issue/PR.

**Comment by AndiBraimllari** [comment]
Also once you're done, if you'd like, don't forget to add yourself in the contributors list (make the README changes in this PR).

File: src/app/home/home.component.ts (hunk 1 above)
Comment (stackoversnow) [reply src/app/home/home.component.ts:31]: Why it should not be changed? Please share with us some cases where this doesn't work or why it is unacceptable. Which other code parts depend on it being like that and not otherwise. I think it would nice to [explain the why](https://google.github.io/eng-practices/review/reviewer/comments.html#why) here. Helps novice contributors make a good headstart. 

As such issues cannot be alleviated otherwise, such decisions and unacceptable code changes should be noted somewhere that is accessible to all. The code comments are a good candidate for this. I created [an issue](https://github.com/OpenCovenant/quill/issues/89) to track and avoid such issues.

Comment (AndiBraimllari) [reply src/app/home/home.component.ts:31]: Having the `innerHTML` to be `<p><br></p>` means that during interactions with the editor (the `div` that contains this `innerHTML`) will work with paragraphs (`<p>`s). E.g. pressing Enter in the editor will change its `innerHTML` to `<p><br></p><p><br></p>`, additionally typing "something" in it and pressing Enter and then typing something "else" would change it to `<p>something</p><p>else</p>`. Having this "paragraphized" behavior is aligned with what the user expects in regards to the writing of a text.

Having more comments for now is definitely a good idea, I've created [this PR](https://github.com/OpenCovenant/quill/pull/94) and put there some changes, let me know what you'd like to see added/changed.

**Comment by AndiBraimllari** [comment]
Having the placeholder on a separate `div` seems appropriate, obviously given if the positioning is correct.

Looks good to me. If you'd like you can revert the deletion of the `typo` class CSS (some CSS is redundant and that should be handled in a different PR) and add the return type for the `updatePlaceholder` method.

**Review by AndiBraimllari — APPROVED** [review]
